### ISSUE TITLE
Выгрузка ключей

### ISSUE THREAD

**Issue by SergiySPB** [antoncst/gamma#9]
Реализовать два способа выгрузки ключей

Способ 1:  выгрузка файл-ключей в PlainText а именно:
- Без пароля
- Без расширения пароля (соотв.)
- Без цикла РСЛОС над паролем
синтаксис командной строки:
#gamma -e sourcefile -kOpen keyfilename
#gamma -d sourcefile -kOpen keyfilename

Способ2: выгрузка шифрованных файл-ключей "по полной программе", т.е. точно также как они сохраняются в заголовке "encrypted" файла.

синтаксис командной строки:
#gamma -e sourcefile -k keyfilename
#gamma -d sourcefile -k keyfilename

Примечание 1.1
В синтаксисе командной строки обязательно использовать РеГиСТр для ключей  "-kOpen" чтобы пользователь осознанно понимал когда он выгружает файл-ключи PlainText'om, а когда шифрованные т.е. с паролем.

Примечание 1.2
При выгрузке ключей в (файл-ключ) обоими способами, служебная информация в файле "encrypted" НЕ остаётся, только шифротекст.

Примечание 1.3
 В обоих способах экспорта ключи (R1, MPR1, MPR2, R2) дописываются в один файл-ключ последовательно.

Примечание 1.4
Пишется чёткая документация или служебная информация выдаваемая программой с адресами (начало/конец) всех ключей в одном файле-ключе, дабы изменив например 1 бит (R1, MPR1, MPR2, R2) в экспортируемом файле ключей (файл-ключ) можно было отследить чёткую корреляцию в шифротексте.

**Comment by antoncst** [comment]
закоммитил 1-й вариант
опции ком. строки:
-gk или  --genkey    generate keys to keyfile
-k или  --keyfile :  use keyfile instead of generating keys.\n"
Имя файла ключей сейчас всегда 'keyfile'
Указание имени файла ключей пока не реализовано.
Примеры:
./gamma -gk  сгенерировать keyfile
./gamma -k зашифровать, используя keyfile
./gamma -d -k расшифровать, используя keyfile
